### ISSUE TITLE
Meer specialiteiten van een docent toevoegen 

### ISSUE THREAD

**Issue by lamartm** [lamartm/cmda-smoelenboek#45]

**Comment by Mitzyyy** [comment]
Er zijn meer invulvelden voor de docent gekomen met hints (dit wilde opdrachtgever graag omdat je hier tot aan stoot geeft om ook daadwerkelijk iets in te vullen). Ook is de data realistischer gemaakt door echte foto's toe te voegen die lijken op de docenten met daarbij hun echte namen en e-mailadressen.
